### ISSUE TITLE
GET https://registry.npmjs.org/seo-pane - Not found

### ISSUE THREAD

**Issue by MinaroShikuchi** [sanity-io/sanity-plugin-seo-pane#23]
Running `npm install --legacy-peer-deps --save seo-pane'` failed with:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-hook-form@6.15.8
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@">=16.8.0" from @dnd-kit/accessibility@3.0.1
npm WARN   node_modules/@dnd-kit/accessibility
npm WARN     @dnd-kit/accessibility@"^3.0.0" from @dnd-kit/core@6.0.8
npm WARN     node_modules/@dnd-kit/core
npm WARN   62 more (@dnd-kit/core, @dnd-kit/modifiers, @dnd-kit/sortable, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17" from react-hook-form@6.15.8
npm WARN node_modules/sanity-plugin-media/node_modules/react-hook-form
npm WARN   react-hook-form@"^6.15.1" from sanity-plugin-media@2.0.5
npm WARN   node_modules/sanity-plugin-media
npm WARN   1 more (@hookform/resolvers)
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17" from react-hook-form@6.15.8
npm WARN   node_modules/sanity-plugin-media/node_modules/react-hook-form
npm WARN     react-hook-form@"^6.15.1" from sanity-plugin-media@2.0.5
npm WARN     node_modules/sanity-plugin-media
npm WARN     1 more (@hookform/resolvers)
npm ERR! process terminated
npm ERR! signal SIGINT

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/minaro/.npm/_logs/2023-06-30T21_42_25_972Z-debug-0.log
minaro@XPS:~/Github/handheldfilms.com/handheldfilms$ sanity install seo-pane
Running 'npm install --legacy-peer-deps --save seo-pane'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/seo-pane - Not found
npm ERR! 404 
npm ERR! 404  'seo-pane@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/minaro/.npm/_logs/2023-06-30T21_42_32_684Z-debug-0.log

Error: Command failed with exit code 1 (EPERM): npm install --legacy-peer-deps --save seo-pane
    at makeError$1 (~/.nvm/versions/node/v16.17.0/lib/node_modules/@sanity/cli/lib/_chunks/cli-2642f8ef.js:1641:1417)
    at handlePromise (~/.nvm/versions/node/v16.17.0/lib/node_modules/@sanity/cli/lib/_chunks/cli-2642f8ef.js:1721:959)
    at async installNewPackages (~/.nvm/versions/node/v16.17.0/lib/node_modules/@sanity/cli/lib/_chunks/cli-2642f8ef.js:1721:5730)
    at async Object.action (~/.nvm/versions/node/v16.17.0/lib/node_modules/@sanity/cli/lib/_chunks/cli-2642f8ef.js:17879:15907)
    ```

**Comment by SimeonGriggs** [comment]
Try this instead:

```
npm install sanity-plugin-seo-pane
```
